class Estate {
  final String title;
  final String owner;
  final String agentStatus; // 'agent' or 'owner'
  final int number;
  final int width;
  final int height;
  final double price;
  final double area;
  final String location;
  final StatusCategory status;
  final EstateTypeCategory estateType;

  const Estate({
    required this.title,
    required this.owner,
    required this.agentStatus,
    required this.number,
    required this.width,
    required this.height,
    required this.price,
    required this.area,
    required this.location,
    required this.status,
    required this.estateType,
  });
}

enum StatusCategory {
  sold,
  forRent,
  forSale,
  booked,
}

enum EstateTypeCategory {
  land,
  car,
  house,
  apartment,
  office,
  hotel,
  other,
}

// 🏡 Sample Local Data (3 examples for each estate type)
final List<Estate> estates = [
  // === LAND ===
  Estate(
    title: 'Ndera Hill Plot',
    owner: 'Tresor Ltd',
    agentStatus: 'agent',
    number: 1,
    width: 30,
    height: 40,
    price: 15000,
    area: 1200,
    location: 'Ndera, Kigali',
    status: StatusCategory.forSale,
    estateType: EstateTypeCategory.land,
  ),
  Estate(
    title: 'Rwamagana Farm Land',
    owner: 'Hirwa Estates',
    agentStatus: 'owner',
    number: 2,
    width: 50,
    height: 50,
    price: 20000,
    area: 2500,
    location: 'Rwamagana, Rwanda',
    status: StatusCategory.sold,
    estateType: EstateTypeCategory.land,
  ),
  Estate(
    title: 'Nyamata Commercial Plot',
    owner: 'Tresor Real Estate',
    agentStatus: 'agent',
    number: 3,
    width: 40,
    height: 60,
    price: 18000,
    area: 2400,
    location: 'Nyamata Town',
    status: StatusCategory.booked,
    estateType: EstateTypeCategory.land,
  ),

  // === CAR ===
  Estate(
    title: 'Toyota RAV4 2021',
    owner: 'Elite Motors',
    agentStatus: 'agent',
    number: 4,
    width: 2,
    height: 1,
    price: 25000,
    area: 12,
    location: 'Remera, Kigali',
    status: StatusCategory.forSale,
    estateType: EstateTypeCategory.car,
  ),
  Estate(
    title: 'Land Cruiser Prado 2018',
    owner: 'Hirwa Cars',
    agentStatus: 'owner',
    number: 5,
    width: 2,
    height: 1,
    price: 45000,
    area: 15,
    location: 'Kicukiro, Kigali',
    status: StatusCategory.sold,
    estateType: EstateTypeCategory.car,
  ),
  Estate(
    title: 'Suzuki Swift 2022',
    owner: 'QuickDrive Ltd',
    agentStatus: 'agent',
    number: 6,
    width: 2,
    height: 1,
    price: 17000,
    area: 10,
    location: 'Gisozi, Kigali',
    status: StatusCategory.forRent,
    estateType: EstateTypeCategory.car,
  ),

  // === HOUSE ===
  Estate(
    title: 'Luxury Villa in Nyarutarama',
    owner: 'Kigali Homes',
    agentStatus: 'agent',
    number: 7,
    width: 30,
    height: 40,
    price: 300000,
    area: 1500,
    location: 'Nyarutarama, Kigali',
    status: StatusCategory.forSale,
    estateType: EstateTypeCategory.house,
  ),
  Estate(
    title: 'Bungalow in Gisozi',
    owner: 'Hirwa Tresor',
    agentStatus: 'owner',
    number: 8,
    width: 25,
    height: 30,
    price: 120000,
    area: 1000,
    location: 'Gisozi, Kigali',
    status: StatusCategory.booked,
    estateType: EstateTypeCategory.house,
  ),
  Estate(
    title: 'Family House in Kicukiro',
    owner: 'Tresor Real Estate',
    agentStatus: 'agent',
    number: 9,
    width: 28,
    height: 35,
    price: 150000,
    area: 1100,
    location: 'Kicukiro, Kigali',
    status: StatusCategory.forRent,
    estateType: EstateTypeCategory.house,
  ),

  // === APARTMENT ===
  Estate(
    title: 'Downtown Apartment',
    owner: 'Prime Apartments Ltd',
    agentStatus: 'agent',
    number: 10,
    width: 20,
    height: 25,
    price: 80000,
    area: 600,
    location: 'City Center, Kigali',
    status: StatusCategory.forRent,
    estateType: EstateTypeCategory.apartment,
  ),
  Estate(
    title: 'Kacyiru Apartment',
    owner: 'Hirwa Estates',
    agentStatus: 'owner',
    number: 11,
    width: 22,
    height: 28,
    price: 95000,
    area: 700,
    location: 'Kacyiru, Kigali',
    status: StatusCategory.forSale,
    estateType: EstateTypeCategory.apartment,
  ),
  Estate(
    title: 'Kimironko Apartments',
    owner: 'Tresor Ltd',
    agentStatus: 'agent',
    number: 12,
    width: 24,
    height: 26,
    price: 85000,
    area: 650,
    location: 'Kimironko, Kigali',
    status: StatusCategory.booked,
    estateType: EstateTypeCategory.apartment,
  ),

  // === OFFICE ===
  Estate(
    title: 'Kigali Business Tower Office',
    owner: 'Skyline Developers',
    agentStatus: 'agent',
    number: 13,
    width: 40,
    height: 60,
    price: 350000,
    area: 2400,
    location: 'Kiyovu, Kigali',
    status: StatusCategory.forRent,
    estateType: EstateTypeCategory.office,
  ),
  Estate(
    title: 'Downtown Office Space',
    owner: 'RwandaWork',
    agentStatus: 'owner',
    number: 14,
    width: 35,
    height: 50,
    price: 270000,
    area: 2000,
    location: 'Kigali City Center',
    status: StatusCategory.forSale,
    estateType: EstateTypeCategory.office,
  ),
  Estate(
    title: 'Remera Plaza Office',
    owner: 'Tresor Group',
    agentStatus: 'agent',
    number: 15,
    width: 30,
    height: 40,
    price: 200000,
    area: 1800,
    location: 'Remera, Kigali',
    status: StatusCategory.booked,
    estateType: EstateTypeCategory.office,
  ),

  // === HOTEL ===
  Estate(
    title: 'Serena Hotel Kigali',
    owner: 'Serena Group',
    agentStatus: 'owner',
    number: 16,
    width: 100,
    height: 80,
    price: 2000000,
    area: 8000,
    location: 'Kiyovu, Kigali',
    status: StatusCategory.forRent,
    estateType: EstateTypeCategory.hotel,
  ),
  Estate(
    title: 'Ubumwe Grand Hotel',
    owner: 'Ubumwe Ltd',
    agentStatus: 'agent',
    number: 17,
    width: 90,
    height: 70,
    price: 1800000,
    area: 7000,
    location: 'Kigali Downtown',
    status: StatusCategory.sold,
    estateType: EstateTypeCategory.hotel,
  ),
  Estate(
    title: 'Heaven Boutique Hotel',
    owner: 'Heaven Rwanda',
    agentStatus: 'owner',
    number: 18,
    width: 85,
    height: 75,
    price: 1500000,
    area: 6500,
    location: 'Kiyovu, Kigali',
    status: StatusCategory.forSale,
    estateType: EstateTypeCategory.hotel,
  ),

  // === OTHER ===
  Estate(
    title: 'Parking Space for Rent',
    owner: 'SmartPark Ltd',
    agentStatus: 'agent',
    number: 19,
    width: 20,
    height: 20,
    price: 3000,
    area: 400,
    location: 'Kicukiro, Kigali',
    status: StatusCategory.forRent,
    estateType: EstateTypeCategory.other,
  ),
  Estate(
    title: 'Event Venue Space',
    owner: 'Tresor Events',
    agentStatus: 'owner',
    number: 20,
    width: 50,
    height: 60,
    price: 25000,
    area: 3000,
    location: 'Remera, Kigali',
    status: StatusCategory.forSale,
    estateType: EstateTypeCategory.other,
  ),
  Estate(
    title: 'Storage Warehouse',
    owner: 'Hirwa Logistics',
    agentStatus: 'agent',
    number: 21,
    width: 70,
    height: 80,
    price: 40000,
    area: 5000,
    location: 'Kigali Industrial Zone',
    status: StatusCategory.booked,
    estateType: EstateTypeCategory.other,
  ),
];
